### ISSUE TITLE
Button disappear when maximized

### ISSUE THREAD

**Issue by ftonato** [bukinoshita/taskr#14]
Hi,

I noticed a small bug in the use of buttons:

When I switch to total maximized window the `add new tasks` button disappear off the bottom of the screen...

You can see below:

![tasks-button_bug](https://user-images.githubusercontent.com/5417662/34562684-98557cc0-f136-11e7-8f29-8d50408710d3.gif)

**Comment by bukinoshita** [comment]
Thanks @ftonato for reporting it!
