### ISSUE TITLE
add shortcuts

### ISSUE THREAD

**Issue by GuiCarneiro** [bukinoshita/taskr#17]
Increasingly I try to avoid using the mouse when I'm programming, so it would be nice to be able to extract more from the Taskr using only the keyboard.

I speak only for my short experience, but I would like to switch between the "Today", "Backlog" and "Done" tabs by simply pressing the "1", "2" and "3" buttons. It would be pretty quick to see the other tabs and check what's on their lists.

Well, it's just my idea of a small feature. ;D

**Comment by bukinoshita** [comment]
Great idea @GuiCarneiro. I'll be implementing this soon. I was thinking just like terminal tabs or browser tabs using `cmd + 1`; `cmd + 2` etc

**Comment by tyhatch** [comment]
A couple keyboard shortcuts that came to mind as I was using it today: `enter` or `cmd+n` to create a new task, tabbing through tasks and pressing `enter` to mark an item done and `esc` to leave current screen (back). Though `esc` on the taskbar MBP is kinda borked.

**Comment by bukinoshita** [comment]
- `cmd + ${N}`: to change tabs
- `cmd + n`: redirect to `add task`
- `esc`: redirec to `Today`'s tab

I think that looks good. Do you guys have more suggestions?

**Comment by ssssamstrup** [comment]
And maybe `space` or `tab`: for moving a task from Today to Backlog or reverse depending on which of the tabs you are on.

Maybe being able to press 
* `t`: to switch to today
* `b`> backlog and
* `d` > done
would be more intuitive to non-programmers/regular users. Or `cmd + t/b/d`.

**Comment by ssssamstrup** [comment]
Well, moving between tabs should probably just be `tab`and then `space` or `shift + tab`could be to move a task from Today <> Backlog.
