### ISSUE TITLE
Website Formatting

### ISSUE THREAD

**Issue by Vivalldi** [bukinoshita/taskr#21]
First off, I love this project and truly appreciate what you are doing!
The attached image shows what I see when I visit the site. It's nice and clean except for one little detail. The "GitHub" link gets hidden by `taskr.png` image. 
<img width="1280" alt="screen shot 2018-01-05 at 8 47 15 am" src="https://user-images.githubusercontent.com/8962537/34611825-196309b8-f1f5-11e7-9e79-105fa2249ae9.png">

Of note, I would suggest _not_ putting the image in a footer but rather a div.

**Comment by bukinoshita** [comment]
Thanks for reporting @Vivalldi. Put this `on hold` because I'm working on a new website.
