### ISSUE TITLE
basic commands not working (copy, paste, select)

### ISSUE THREAD

**Issue by pwign** [bukinoshita/taskr#23]
Loving the project. 😍

Though, I can't seem to highlight/select the text in a select. For example, when typing the title for the task, it's not possible to _Command + A_ to select everything or attempting to highlight a word by dragging your mouse. It works, however, when you double-click a word.

**Comment by bukinoshita** [comment]
Thanks @pwign.

This might be a bug on electron. I'm not sure yet, but it seems that the `cmd + c`, `cmd + v`, `cmd + a` aren't working
