### ISSUE TITLE
Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by yeskunall** [bukinoshita/taskr#30]
<img width="682" alt="screen shot 2018-01-06 at 8 21 32 am" src="https://user-images.githubusercontent.com/14703164/34635802-a7f08898-f2ba-11e7-8ae1-149c798b8419.png">

Hey 👋

As you can see, the binary crashes because you are using the `autoUpdater` API on a non-codesigned application.

Maybe there's a few steps missing in the README? 😅

**Comment by bukinoshita** [comment]
Hey, my bad.

Can you try this?

If you have issues in the codesign step when running yarn run dist on macOS, you can temporarily disable code signing locally by setting export CSC_IDENTITY_AUTO_DISCOVERY=false for the current terminal session.

**Comment by yeskunall** [comment]
All right @bukinoshita, what you suggested _should_ have worked, but I'm still getting the same error, although it does emit a message saying `CSC_IDENTITY_AUTO_DISCOVERY` was disabled. So I'm not sure what's going on there. I'll investigate a bit more.

I had a question of my own tho, that came up by playing around with macOS yesterday (I recently switched over to macOS, so it's all a bit new to me 😅): any reason why a binary needs to be created before we can test the app in development?

**Comment by bukinoshita** [comment]
If you want to just run locally you can run `yarn start` and it should open the app. `yarn dist` you are actually creating the binaries.

**Comment by bukinoshita** [comment]
@yeskunall were you able to run?

**Comment by yeskunall** [comment]
I can run `yarn start`, so I can set up a dev workflow, but setting that flag to false didn't seem to work for me. I'm gonna close this until I can come back to you with more on this. Thanks @bukinoshita 💖
