### ISSUE TITLE
Doesn't work on High Sierra 10.13.2 (17C88)

### ISSUE THREAD

**Issue by ahmadalfy** [bukinoshita/taskr#35]
![image](https://user-images.githubusercontent.com/87611/34651329-75eb902c-f3d7-11e7-96c8-e332185c8ddf.png)
My system:

![image](https://user-images.githubusercontent.com/87611/34651337-8e209106-f3d7-11e7-8b36-06abf826e802.png)

**Comment by bukinoshita** [comment]
Hi @ahmadalfy, I'm using the same version that you're using and it's working fine.

Can you download the `dmg` file and try to reinstall it? You can download it [here](https://github.com/bukinoshita/taskr/releases/download/0.3.1/taskr-0.3.1.dmg)

**Comment by ahmadalfy** [comment]
This one works, the other download link (the zip file didn't)
