### ISSUE TITLE
Release for other OS

### ISSUE THREAD

**Issue by matAlmeida** [bukinoshita/taskr#37]
I saw this project in a facebook group from Brazil and i got interested but i only use Windows and Linux. Are you planning to release versions for other operating systems? I do not know much about electron, would it be difficult to create a build for linux, for example, only with the source code? Or is there a lot of specific stuff for mac?

**Comment by matAlmeida** [comment]
i got it, sorry for open the issue

**Comment by bukinoshita** [comment]
Next release will incluse [windows support](https://github.com/bukinoshita/taskr/commit/32249b28d20cf36f38aeb8b5fe6a51eb36752ab6) and I'm figuring out how to build an [app image for Linux](https://github.com/bukinoshita/taskr/issues/5)
