### ISSUE TITLE
Mobile app?

### ISSUE THREAD

**Issue by iRoachie** [bukinoshita/taskr#39]
Interested in doing a companion mobile app? Cross-platform with react-native is what I had in mind.

**Comment by bukinoshita** [comment]
Maybe, there're a couple of things I want to prioritize before start working on iOS like `cloud-syncing`

**Comment by iRoachie** [comment]
Cool sure thing. Lemme know when you're up for it.

**Comment by bukinoshita** [comment]
FYI iOS app confirmed! 🔜
