### ISSUE TITLE
When marking backlog task as done, it appears in Today rather than Done

### ISSUE THREAD

**Issue by jsit** [bukinoshita/taskr#45]

**Comment by bukinoshita** [comment]
On `backlog` tab there's no `move task to done` option. Only an option to move to `Today`'s tab. You can only move tasks to `done` on `Today`'s tab.

Let me know if you still have an issue so we can reopen.

<img width="354" alt="screenshot 2018-01-10 19 22 27" src="https://user-images.githubusercontent.com/6929565/34796109-a605a020-f63b-11e7-83be-1e54d6c2e32c.png">
