### ISSUE TITLE
Pages margin-top different depending on OS

### ISSUE THREAD

**Issue by matAlmeida** [bukinoshita/taskr#46]
In linux, the `title-bar` push the page down and the buttons doesnt appears.
proof:
![old](https://i.imgur.com/Lg8fQsD.png)

how i solved:
`renderer/layouts/page.js`
```css
 99| section {
100|   margin-top: ${window.innerHeight - window.outerHeight}px;
101| }
```
![new](https://i.imgur.com/q2tKlpc.png)

What you think?

**Comment by bukinoshita** [comment]
We don't support Linux yet @matAlmeida. Can you check https://github.com/bukinoshita/taskr/issues/5 to see if you can build an App Image
