### ISSUE TITLE
Responsive List View

### ISSUE THREAD

**Issue by alexandrustoica** [bukinoshita/taskr#48]
I was thinking maybe we could make the list from `Home Page` responsive. If we add an event listener to `window`, we could use a state variable to adjust the height of the `section` element.

Anyway, nice application! 👍

![Responsive](https://i.imgur.com/51QagdC.png)

**Comment by bukinoshita** [comment]
Hey @alexandrustoica thanks!

Did you resize the window app?

**Comment by alexandrustoica** [comment]
Yep, I resized it in order to view all my tasks, that's when I realized that the list was not responsive.

**Comment by bukinoshita** [comment]
Unfortunately on [v1.0.0](https://github.com/bukinoshita/taskr/blob/v1.0.0/main/index.js#L29-L30) you won't be able to do that.
