### ISSUE TITLE
Regarding next.js

### ISSUE THREAD

**Issue by xavitb3** [bukinoshita/taskr#54]
First of all congratulations for your work! I'm learning a lot and I love the app, i'm using it for my freelance projects. I've been looking at your code (I'm still learning react) i've seen that you are using next.js. May I ask you why? I don't understand the benefits of using next.js in this kind of project

**Comment by bukinoshita** [comment]
This might answer your question [here](https://leo.im/2017/electron-next)
But in general I just wanted to test `electron-next`
